title: Tim Konle # your name (or website title) here
logo: "/images/Shooting_Syfit.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hei! I'm Tim and I'm a Software Developer from Germany. Currently im working as a Junior Developer @ Syfit GmbH. I'm responsible for development and deployment of Rest-API's and microservices, mainly with Python, Docker and Kubernetes.
  <br><br>
  On this side you cann see my Resumee and my personal Projects i have developed over the past years. 
  <br><br>
  <a href="https://www.linkedin.com/in/tim-konle-3378a8239/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
